---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-cloudflared-token
  namespace: monitoring
spec:
  encryptedData:
    token: AgAEiJJbAygn+V3lehEj42NK40kAtTJgjxBd1zMvfkROV32HkyfctKWE6Tf1/3SajVlXVn6RRp5bSLt/+b6hdNTIfKlng37wtZS5lIieGmwcA8tRjg+Cv9w/quhsNbyqOoiydX86LvQEhDrkFITpqU5GivVKnoeH1I9rWzc+N8Zj4F1Fq0wX2+fvd1scujK9LeyvSD8EEyetGrIlciflR0irIXedcS1pKWDYcPEop1B3W6TBeFf4CWifbuTZr5k0nBo3ZRTTQYx+oNGHv1PW/HhT6wjIVMqBhf0IFetTMp0uucR5LRvQ486SpPZdwbnjEpa+YcqolH6XcuZju01WagR0+BlH/2W1OgxvxEVn4hWWmZ+VSM2AvRPGI4ES76Vr90mY6+qsvSnBL02pvjVhyygI795lvhsEmehhjF9FBjuLvdiVcnaNaxtr0AMYLwz8KMV2gbywYTXGNQXis+KTx5JYu5rQXfkhX3BWiPr3LvFu1qNnD+Y9lGS/sxY7/WaqOJNpcXrti+7525yUfrL12OricsiLip67AFlSLXdUBl0fmO20ewmuRii/p1PLN4PZYK3riDicfXSk9EiOHrCLlYDLw2aqywB2JApDuMgr1dFkCgCNqgj4lOl2ZI3a384G7i3pRE/ztrBETrq5pb+45Wg2Y3gAjxFTwxLiQIzCYqUeLdIFMur7OC/v7Clgoe0+Tt0lzHllDSfAIdiYrcD9Dl1Uffjk4+bcbahEfFDkRDp7BwLw5yENLCR/N5KR3mt4FbzAcF0paxUV8vBJ9MJazUvWO0OxozaxAigz/LHFVXEBXhJour0h/NPapZyEyoWwdgflrgRBVTPKjq1b5EP0tQ4tSQPLEDbHyrcUKa+V5RlIWaoOk23kx8FGUoUaGtXe40H0gmolY4xMFiKxv7HrVgS1EJ+r6rCRgu671jJKGfv06MeZcXyINlk0
  template:
    metadata:
      name: grafana-cloudflared-token
      namespace: monitoring
