---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAbt1dYRp19AlT266HEu1dzfkfbiIlWkGUXuXpUQ7/JuHrRZI5f9CXPaw5k7Lyr+8qKC3TscTH7CEjGkXyFQeTaHtb+4gAZ5zB1V0kqGr0ojD64eDDy5ms651Fyx+hbIW0aBAz8eh5UtuNp+5V64BCvoRc+xwRSS1rvoQC0MCbiOFEta42F9jU9/mhdKVzeV72tFSg/gg6yc8qPBGAJw+9og+hDHgqhrgTIcECTYQGlWjS+0bjmfUdQB7jupjUX5BVq/kPYVIMudRXqzRQeV5TDwRJuRMHVhMBh/dr6Uqb9nRdFaeJHfqWUTRxROFNmwdE1vS9sCBg/bZ+hIiqYqRu+N/iSQaEM1CVZMfxjK129i59Ppm082eGZGGFR1J+1OtaeK5CCgOwrwxXVe2kH+v2PqCuBfycSLywOaRWXF6qbKK/tIk36bspA/7WdTWKakKSDmJH696gBWun6FIpVJsrS7lnjIu+y6OAbqYs6i4PmmrPOgYRUsMLk0MUZLw6HPhKrLiVMMWhw21eBDK6HSxOuEzbY0FZz60TU/PTl6NoCKc0jUNO+UcITke6kRIwq9RpoV0YWpucduTjhIyDXyx4j+o1A419Pgl1iO+iCzXLdt5CCeWptADAFRdRar4Ch53R7RnjSclZtcXsSoNVIxuHvxBgXN3jzY1b04Iwaf9mtKJa7/YYqvL+/83L/ykQ/3uHcUS3YfprhwTuul7hX1PTmfYGvibZp+kXs3+ZE
    admin-user: AgCHvwt02ZfhOXSxGMaJ8hIXFyadKoiiqk89pYavD4H4Gjc1agbBdAJFkVBaPUezad1OF3zFJHup2ESbRYnakJQDwwUdwvQKjakPvNDr3fqIb5e25nGnU1ZNOUcWvY1Nc2cG03gCeG7HwjP5oeRdfEcvlpATVlOvXY1pX5FiT8HYVEax7LXtbVZAStXxYlLikBcZZfYxcRWF8NdJXsfCIySjbXU7EEXVwkMw5U+xXzN9rjHTLgDAR1bdIg8hebNwe5MnzZOKlkH0dvx0wK5I1B1ximqHNli+jA7O7YfZrS/CYwJLOLYOjIOpjbU7ClUHuKa1dGlin+TCKnSXiEabjecT8p/jwPDcAV/YI5y5ky7M/yGmMNrbX6SktUaCWFv4QV7KLTjnsP1CpB4rEe1pLUo3v/eAHOTKiYDa/qMhClMr1Hn3UausPAwLlcqrgRzQfpBHpmNDkiZ+l7xmlXYnebly35tZ2vnRHxxl7KCl5er/RJ0/8f0D9gy9xYfbbEZpKCh72RwdTAAeCqELfH0/p7lQtw/xKGZGB4yvMNAanl/CAfq8y5xu4B3/Dfqd5GMXrObnhCnGw5dTJKGX9raQQ4nG+iMvGHrGJYDi4i9sARBvRA1ajDNgxG+7bHXe70TmgEzfrKkDVlXrNl5NMmqzTf2yCnlenm3FoYPWXz5I1R0RkYFiM9TETfdXVt0hXOUO/Se55/JqQw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
