---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-alert-webhook
  namespace: monitoring
spec:
  encryptedData:
    url: AgBVhCFYLKC+Ytbh3/ei2Gb1haA0tRPV8yLrvBY0AUSRkhw6eynK7g4Et0iGMilvz37mX7PUn50MOKDPz0Fc9ArdZSo3g8Yif/N8v30LTKUHUnbShWwUE9RiSaSTPrDDRRj3eRwksZVIwAOh+wTt8DyDDF19izyf1zAafRf2aiUcOWqogKcHt1GdMbstJXPwzWqF90EVUlsJFvdNQIJr27zSh8SyHQd5ReHwvRxpsTEv9zY6IRTNFe31DYDOH08Ylht6NT83DQG6+dawtB4lKrL4/A8QukzBUoTvL/MSs0VN1JjT+GkQfl5Rw+SKJLK/mVXJ9bmRlHWjfXKBep90cHtyRjhme5h2M/hh/DMzDcv+CKxZCdEbtGqObSZeUW6ju8o4K8PHeIoTXv6I0RHBZFMvCzy++/55BnPmTU39xeOr0KPfxvGQz9/Sh8lTTxMVmEhzSTm8DTkdYtxg4YPYMqfTbhgWXWSrxygyLSiv9TjuRmDxBKmNPtYhvPKf35YRgS5KOf1S1r9fjiaXjE0zg9bZyUW2mjzpchZBHpr96LMenKmx9vQStjzvWfeLk7exMDR7tKJoFjGsV13xlLYXKY/bZo4KVSyqOG3gGNU7FaIho+2R7C5lmBthpo0mMRTpHOk+kLzzDllxDHmCpQ4SgGPGLccJzofyd3sNgKKtnmUnVsPjS20oqvufgvi8O+NHA4nB2Ct7ReGnjIJnWT6woYT8TGK/Bhaea74urIdN17whw2jUdGgjVaDlBx0yCfHNKBiJFMT2kiY4+EhQ
  template:
    metadata:
      name: mattermost-alert-webhook
      namespace: monitoring
