---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pinlog-sentinel-receiver-auth
  namespace: monitoring
spec:
  encryptedData:
    PINLOG_SENTINEL_TOKEN: AgAlAPxCvNxaxD86srs7m+SgEH6Ulek2l8srdu33QnE+mZw3goEVGXyTzemSxNQAIjxD9YfsFputGS0/SB9xirCWa1O5Mzf/URBRByDvT1jpThrjyyk0W0NlhXUjKO71zTnmsRCnukZFI3bm1CeMM9t5e1UsnGSeMk4aK7/T6L+Z61lXtwJ10swgiGrzj1nzg8R/J5IO3e5lLEpljGxoxAXKsEOyzzGwOLyy3EN2qFZex8qLkdJKT6H/I0i8e9IaSP/aatgkCzz+WEKSa92OkdHNSklZd94mMAiIRlddRuJwcogPHwoZOLngrDh9749IAivvndZpgSUcYd3Do5wSle4ayO/S6opdci/5cU8HNRllyhIR0E+sZm1zM/lRZhTQKJ80tQARqDOhE6ED75VRBU0olC4l2HVa11Cb+ww9CKRHA6ahCbqjtQzZxncvGN7tvQPKazz4t2btKh0LE6x7O9Mhk5PLpkawrLcFP3StQti7XQTgk+vtyH3/lZRQNoC6JKQYYswv63/CkQcVfTyZ5aHqhrb9ZBDnfl2Hn5gjilArlH4+6XFVXDPlPmRK+Zrcn/GQRMdbQVDG5HUomYkOGA3kUzgTAxxhK7oBJzsDubAvLKpfo7O37QoaBWoB9iD6vTxWP/b+jeLYjQvTc8Nn/Lcqkolnz9Q47Op+09NGn4T0xNVJAKUR/f01UoejpQvKbzoXpPq3HW7YbehCD+AwVdfaupuuk4QGIO3BcX/WUmPENToN9x9wt6L2dgJULGhZCds6wDwPuXUdquiPHBSNmXRM
  template:
    metadata:
      name: pinlog-sentinel-receiver-auth
      namespace: monitoring
