---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudbeaver-cloudflared-token
  namespace: pinlog-prod
spec:
  encryptedData:
    token: AgCQ6T7XZhjosdfVv2GUFSu5K+DOSarFCkSzgeQUpeU0+vtQjYPaEIiHLvHQwUoXJ4gkwWUsZn2J8Cb/n0NmUJZHTq+2Heou4F9YfZ48Y2az9Vod1bh6SMGd0lHXBhfPwrg2PGwM1BkcWlt1T2EJ4IooBF8FTB+gMgBFP82CA9+6x/iUXNH5XIrrJQKRwdv/tl/SOiWenx940RQqRrf90wF3EETGvjJDabG9iMeSdONFdim+FN8yJPsciWo3qln2bg+HyFNs/Y98CAuKG3Q95PZTea9tk0hbrgQi/VTf5cQIyZVbfawBTM3BGRj/lSFKXnmxlfbkzJQt+4vpaUNmm5BDepN+Ebp6I+J04/tEolgjmfYLkjxOx4kT0RxmA6BNS8+6fWxT5/XRDgha/exHFOyaKsuz9uwTzN2x4OXgWL+ec8GNyJykYYnNPKGZMAoGIswSngk0SpcGTIQqKTpcof2SQ/i68Z+Jt0XpNs1b0ynisgoNIxYsX4l1u6VytpWfeLk975gwfqpAzvhPzUoQPrz/zobQM7G666Zvno5Kcnb9zb2D9hhm4+oNrzHEGp2a1s11xlGkkQlj9yHrnqBYJ4TGO0FN73IREhhwXvMAEvRGkrd22Q8TrK9qalwi0Re3aAP0Fd0uEhPoXIlOEDFHnqO5gDpQ/Pu34QPDlDJmna3cNT7MNJwl8aXZYLsBBWM0sU6VFfAk3G7J+0awJaZ6ohzDOSbrY32M40QIqtOlG1+u+o7CvjQey+FiKuxyrVJVngV1tbHM5KovN1M5DWFhQhtJRi/WiBNgObF29gE13owdEgksilqBnkkEl33oCbWOVUFsMutNqwPUihuFSOYesnFFWRxF8R7NUAIUgBjy4etZt43zjwKzvqQZd8UJiiW2e1uBeYLxzyvB0HXFrmrVx8OLHN7OrM6UQ/Y35jLS1if8bBEugIJx/pvF
  template:
    metadata:
      name: cloudbeaver-cloudflared-token
      namespace: pinlog-prod
    type: Opaque
