apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-back-pull
  namespace: pinlog-prod
spec:
  encryptedData:
    .dockerconfigjson: AgCztKdOdk/bc8AyCUk3CoGIWFE8dsUpAkz3DvPwd1MKdaRNRnoBCUXIgQBJ+LA8QZQghxlRoynGqHv26HkgP5sk+v//d92nntMbUKRPyy5C4fDp8atO8FhKwXrEwHMXZK+SjvjenbD06EKpStCWtkwpWUv+0afQrItKM4MXgr4UsFyVPXZ4dHL/GCS/rsrKtFrmsZFbEyYuDmWLaDDfqyUO/eIp7uBDwGc/ATrIY+zWks4obids5TYIdAcsryVWpuS7mlEIqbqRyuc/hYNpcfWScmxdlxl+2TGkxjdgSL7CF66hd3FVhi38l0yv8fE8MR9OppaX0pYiQY5yUFodDms9pQMpY7peGNVNCngOzRa+o56Fry5257baL2vQTiH/ecZtXqLsepyimGWq2EwUxJ7+SzCHra2lE+vmt5pbVdUi1hlHluhh5jvdsVX3k6N+eV6qScgcmYDUqbtgGwyy5jWl2ofVLD8UPnLS2X3mjnQvhFnj3uIa4t4vHxXowD5lBapSD2x2HLJRDhOJI1HRROSrihbKMe6qGWj5i9L9uCem2Nr1lqleCCVZpWCxe9Zgm0OMsfVJpq1jyvYt50BKKGFBNIxRzaotIC9s7Et9vo4ZX2NamMrICR9gnOncfe595lsv4r853StD7VsP1+M1H3LhlS/cI3Y1uyAtgAM9gGxNnL6TUcmtxFPACLhYGaOW3AzFgxOWnpCfik4VjKlfSFLKbUVnw+UJg5+LIIT3jLOEeRHjMrXNeExNIHJlIR23nwKxnSWYlzVgw+ABG1ZxjrBxCENLsmc8F1AdjIV5jh5xIDVoepZDYNLIX9VVx3MB4227jKwQ4XA46srFjoa9lyplF9qCZPKBiwhDyOwquOQJMpzOq5lUdLwOQGhjmzOEa3nt0eT9ANWU/l1IgIPpsuR69/Py0NAGkD+bRjmz568ad9ck
  template:
    metadata:
      name: ghcr-back-pull
      namespace: pinlog-prod
    type: kubernetes.io/dockerconfigjson
