---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-back-pull
  namespace: pinlog-prod
spec:
  encryptedData:
    .dockerconfigjson: AgBkkJmVf7ivO60aL0Id+VCTKeEWpxcCmUkEzs3JjJ8OxipfEntFZNjIY9UJgPBjpJeW8zYuX6WHtj1EembrByXunVYkEB2z5c/ZoBkMhMF1aaXtWXmriEtA7T1vcLJMRqFXxRN3R0cNBHgPUDZblFqv7Ts+IEYOlTqtuHE731SJvyhs0GZwUApHGr/T91OhLTdsfHtMmVo7N+BChBLiy7TOnW6VrxPeCwJ83C6AAYvomDyMKqh9eAO+3bu4Tqd+77DrODzTOuU+3oqpTCa7MQC93giFe8XdwVqtc//6t7LZt0XL6DFv61+Es0PsWN+6BiDR20U36cHlVTnFO/qnUioe8VqvubC5rv3sLJfko8iLHWE9EAOPFbNHzmYYHObhzqwscZ5h8LoyBeQvz2yN88NcoHc/qWNykTwp0g7yp0o9K6jiUiOARc+b2IW0PSCLnupYZEHvfP0tZCa1bWaLYMcaFZ57DdN6stVXbW3SHtY0zmFJCwJCrRvFA36P6kjbIfp22Jut/fcb3xf6c+oPlImrZrAI0vskLf0N9UB1mkXt7SVgZLk5PLRlZUMm5PwA981EQC4hWQxHQ11mp2unQSe5UC0aePBxpEPKK+HIJU1BZeoesYANyTAkpv/tElQBe1F1QIA8mpLwvwX8aFa4vTIVj5YwTGL3h6jRfGqRJdNco5zImjHMBwbctDMjPj1gmV9/1uRgt+u8YefD3HyxN3MAJS3kj3aqG6+no9/Q8dToR1I6D9HuKvg2A1qSguW4z7llP3JR9LQLiFQbRH/sJJMmgGc/r0Ee5Y3NAC9sZR8aYtsJRwDuZ8RZ2FNEMiAz6tnjpWBW0N6iuqMN0Qc+AWK498NKyUhI3JXQfAUY8g5B/YX4GplY3v+spPAwCFC7dr52cV29PaO26Av32vBe12H35UvoGGc5AQGDO7Of+vHsG/mP
  template:
    metadata:
      name: ghcr-back-pull
      namespace: pinlog-prod
    type: kubernetes.io/dockerconfigjson
