---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: image-worker-credentials
  namespace: pinlog-prod
spec:
  encryptedData:
    WORKER_TOKEN: AgA+tRFV3JWAzJzBxmrKUCpRlj8veu2uAE4o1UbSYCFibehSF7cvv4wqF2cocHO6bJetyWd8T5/kNLDhjWEucc8H/xDI2ANwyFg4drpJZJQiF6Rq1ur3Ot1el1xuVQExYJZMU1uUuUljhUE0udK6K3wlEHj7YTSJRZ2HH+NpcSZyWSsKKthE3x1kIMS8KdKsus0HN4CCP00kcrpqY8s+5MPDqAw2CM8tIkIEYgdCNSgkk6+FV6ryRUgAmaHOHOYCaYz9yGdzkPoKZiUkD0eDEvgpsJkqqElyLYMLck8mZvZxnqilFrGnom1pw7W+ejpAlmL8yICrcldTUTfAuZJE5Xk1eG/V3fW3EOkih90rZyB3NNsYwQAlcXp67Dgsx1kwXi3H7nQQKHzoU9zJtZXNRD0dm4feErnmW/0e7sv6HbB5yL5Yi8jvMsvqfhHE2EMafpHJ8YQ7Et+LaIMmxM63/vDklfzmjWVtG7B2txAgxHK+Svqvy/7mzw8/+Kz1ZXQlOdNZLTmQZuS4HzEXz0Hjdl36XytyD22zIj6zEUzdSYLy/ieJqGQK+K0CdZbGCXxfQv4OG4rfd5169M9ei70tIN5Uepb/BkOINqkgUFLPyXk82WH1TQIk6fIrOAYoCHdulGz1aDPL2/E9R+tz4LMjr3ne1GFe3NWoM0B4jCyGWCnCPH7fyPqEtigle3QcaxiR1VDYGqetHxDSr8TngW8eF5riMZfgUSszbMK7bAiBbgDJ21v7ee//z6jbkUChW5dOVlb8OaCPXAiRCIjO4BjDNCTG
  template:
    metadata:
      name: image-worker-credentials
      namespace: pinlog-prod
