---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: pinlog-prod
spec:
  encryptedData:
    password: AgARgqVpPqX1TuRqS9XMCWhA692KtbF1b3YCGddlNjB4bBQMsfni/ll94d16YUcnV9T6QH7WkLq4LnLVWr5YQGQgijglzZOcf0VanuF1V+VsLqRyZWjRC/+U7PIO9pbJ5zb/7GP3dihRcpl1bewTjxVsnoFGbLmgoHjIT1Yy2F8QknlnRkU4R9pV/9XdLU/HG6yuDLpBc0ZpW1hBRkAzhIDjBhdGXMe7i5eDJCZGWvDmWdKBmf3Cgvy9XNWSkEr+BlXN0oht3kk//HPkzf9YUrW+usGYl07Sp17J8kBGaxOz13oE9YeibObnGQ0R4Gc02q0c6lmmtGifKTr83HjjjcEpNEMtrbe5e9qjP0GpKm7YWFBvZ31q0/TXDHrQnGnzWgUBU1/ZXQLOqvYFi1ImxrAQPL1n9ilFfdPOaE2ymYlitLQCdEznDZ6IykbG9eE10agSUkIuDPAegRk//RJB/VzF1T8HVqdpamt7Q7mQ+0o8y9v5iXGNR/Ky20x8dbLRld1hInSvjPY4FEfp3q/yKKdAJWgCH+yGkbdaBC99fkRsT8pOSrwJyNYQ9mmVrkJvUAQhTlb0dv9j4ie09PaYZJL+Bih7pOXimImTwcprwvvALzhvqRxPoapyd5LLnvv7Xj9r0XqdtqOHWsYU5MS8wbJP9RLke4ZClopYLjwBbNloZTKAso4MQGM+IZttSpsRV04yrAJZc9t1NpgtZce91DdG3Q37csm7ZmAWB87MpSsrVswk0eR15ma82WpfpY2m1s4=
  template:
    metadata:
      name: postgres-credentials
      namespace: pinlog-prod
