---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: pinlog-prod
spec:
  encryptedData:
    password: AgAUUlT8DemMZRb7u3S8la9of7G1IGZpwIitQG6nBXUwCQfJb5pBM8hDvBJnqTKjDrIWDlFOlVATnUgA+Ma0fimWkpZxNlLDXtAtNetkZM7SAKCx8qnzgygcwA2RdmwwWZ4rbgKLXX0P5ulHSwN3JT88KbusVJR2VPEmRzNL14t3z6vTimOWACHG07iALR/qXmXxrXGBpWgbFNtmM3CEgCjFhpWycin5W8/FZdEIFE+l1MQA/XquU6Wl6pxdueEaKmQg5T9u+VnWO1A6UEW+NilOwgo1rAaOJY0lgC24en0iWJG6tx1qymygi7baDgOCDfDzKHkZcUGMQfoJleXEfsKQ7fvuW5/s01HVmYhOnVBUt2TkmfKRBeLBTf1pj5xvjLm2iLmi8jviytBbg2fSuZyc8DCFHTUk5/bXl0MPB5FVfETXI8mHgOZIEl+0hyCuEMBsjE0kFuVMPvAyjBDD79tmH3h9fV/hYvKdfwv0oPkqaW7jOX24PBAcTrgO8L+bixEbrC3skSk3pwpy3ktG6U+7JdnxWabai2s9G7HgUQ+nbkSDI1d0OP+K+dv4uOj4GrogKmfcZ8tursamLPpLFQG0moax3oSVSmmFpsw32zgJpzzgm5EB28DMEgt+b//z/WKi4tMd6kvcOaKc7kydqHiP35GczuQ9QLHzXV5IAPZJVMl7T5K9rdfFlzlNe/iixx7cQUDt36OpPxpN9RY/bPSn7H6q+WYpgfY=
  template:
    metadata:
      name: postgres-credentials
      namespace: pinlog-prod
