replicaCount: 1

image:
  repository: ghcr.io/team-pinlog/back
  tag: c75151c42bdf649b604af1e0bfc56e315d5fcf11
  digest: sha256:ed32063f9a9f2e6340c190c9a62c22d6a8ba40a54b82f52b40de09429d76620c
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-back-pull

deploymentStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

terminationGracePeriodSeconds: 40
lifecycle:
  preStop:
    exec:
      command: ["sh", "-c", "sleep 5"]

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: traefik
  host: i15a705.p.ssafy.io
  path: /api/core
  pathType: Prefix

probes:
  enabled: true
  startup:
    path: /api/core/actuator/health/liveness
    failureThreshold: 30
    periodSeconds: 5
  liveness:
    path: /api/core/actuator/health/liveness
    periodSeconds: 20
    failureThreshold: 3
  readiness:
    path: /api/core/actuator/health/readiness
    periodSeconds: 10
    failureThreshold: 3

metrics:
  enabled: true
  path: /api/core/actuator/prometheus
  interval: 60s
  scrapeTimeout: 10s

env:
  - name: JAVA_TOOL_OPTIONS
    value: "-XX:MaxRAMPercentage=70 -XX:+UseSerialGC -Xss512k"
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://postgres:5432/pinlog
  - name: SPRING_DATASOURCE_USERNAME
    value: pinlog
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-credentials
        key: password
  - name: SPRING_DATA_REDIS_HOST
    value: redis
  - name: SPRING_DATA_REDIS_PORT
    value: "6379"

resources:
  requests:
    memory: 384Mi
    cpu: 100m
  limits:
    memory: 768Mi
    cpu: 500m

autoscaling:
  enabled: false

persistence:
  enabled: false

serviceAccount:
  create: true
  name: ""
