---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ai-db-credentials
  namespace: pinlog-dev
spec:
  encryptedData:
    DATABASE_URL: AgAXi1pIUJLkzpiphyVFY92QRHdCxf4pSpZW2wAOaZfqrvBrbxohknDkMhEV0I6k6fTIRA3URXiUs5CX/h5GiNK9kBCjhJ3xGYQ1MmVEqtHvvf2/Cx0JdcyTLLt7kTE/6wq/N3+CppsovLGcWE2n/CAcZA1sI+YIQrZ0Xv1u1SJKAArc+RuaAwHaPdqOVk5e5jjOsyLrPoHuCGyQmuLYRLCw10/n+cAr7QpHdi046h4LF2vrXigXEz2cKtj2lndsj6PUh0R9FlRtvSF1Dn9sxy2U8mc5OxfF69qHzvLHZzW9aN8O4NRKdBPyt07jgbt5HwYoHQTqs8/YNLXQ47KFEWEJVNQf7iB4bWmw24MzpvKQv/nVETvCcFdNyhI2FnfI/FfBG6hXnPsJLEJlJA8Whmjc23yC/Yhemw03Qg5b+KbXsTepJMw785YJJVU6ZWdB1Rh4oTkcOWCKa7QhQqpi6b7jCQYLK+imCt+KqFDOA3kXP+0gpA7fi+H/vzUfBNdgLHrmg0X29GQ/qYThnbcviHFL2tZk3kJDB7iUsY3V8kaY7ROBBPfuZsxCwQ/4D/HRPvR6IUacXnddxXNsVdI2t3CylA5Y0R4Z8qSqf56+Z5u8RVLAPHbNd/XOmmBsOkH/Wuv1Uje1ZBgg7hAPZyfhzlefbeYpZGHsTFeua5CNETfYMroVw6eGH13UZ8rblKk3ZCYvuKHhserTM97yyCDy/kpe9KJhyDIQ3Tk/bTNMPh+HQID2NeG+djSD7jqCGKwQ4kbQ30b5EBc4pC8vUeXXfd0ie/qOgUozOlhuvIe1LQG6XkN7dcGAho1c5isIsixThQIyUAEGw/aDfwS96BPKXWmrMmy1FlNXYkamRPFx/5AxXeQWuxyroiJJQcl6SwIq
  template:
    metadata:
      name: ai-db-credentials
      namespace: pinlog-dev
    type: Opaque
