apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ai-db-credentials
  namespace: pinlog-dev
spec:
  encryptedData:
    DATABASE_URL: AgBhS6TgNttFMH82E3WCSQZfNzS6hFPj7xq6xtO6m69WCrJk5xt5/KdtUnKs6PcJlI3KiSvQDVVNNf1lV7mQBIEvA4+QR/CA8HPqoC0ICkKR7ZpnVpGRif6JOYVN0quJTX92oodYY9vKMAUggJ7m++B8gQ6dgvWc+n2XeJIP60wijW7pVNTclgBCpnpL7PQyc31wB0tSLor6KGg/Jb4RhiC57ZH8aKF/92rqmbqwGJBfAiF3O4EsYoiu+L8TQ+G5O54JBjhE6oQ1pcimRHhJ/n/DoN+xSMyyS0TlOsVeoEnrVImH+4LsRzh+ThXwh6zehkNIaAai9b1IGWeblk9J0/KVnRBw0aWc5ylftCXzuIajI6jYFdXsmhumdgXschGknnXP3CXaCzazRKKsZd3hYAGj4CbH1UO0oDxnWNgHJeVwfl8ZJUAm2R+fmd/R9YLqXXVO861atwa6elmfOlVNqmA0cUFCNNH+3oHsMQ25iW4BsuzART4fztw2/S8XDBChToEgLQxf864pol3BPS7RmRbqWb0UE6V8Q1Pe9CgsIZvZkB6kupjJN8xilfOvvbefWQcZSRsz7dj+R1Y1yXJkIvp0pg8Q7xphF73MYd7V6YukX3cMR+lWCYauIylr/r7jnhNbp4xFMGw13myioFFO1wmF6FTAF+ah1AbeDb6SaegLLKyTGZxpA92m/2ngjcEXuHUjTayx4XDrZkg2MQW3rQzOXsdFe8b2RfJFu09F1sDxijiL5tIxr03/jNqrQD2qW+qzONqoBk1Mo7J5Xqtz3ClHkb/1qaVf1bHP1n0FkovUNwgvP49sIwH/wTmrA+2o658oy4dalgI6zJqdOKJmiCDqi9982/NEvk2zED/pVgAFcuS4NbPxvqpSFGZeqaDfF8dElQ==
  template:
    metadata:
      name: ai-db-credentials
      namespace: pinlog-dev
    type: Opaque
