---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cowork-cloudflared-token
  namespace: pinlog-dev
spec:
  encryptedData:
    token: AgCFK09rCFBhVkkNToudAomDcCnFik5EziHBUKqZyBdO1NxH+cKf1QYY2M/CXFI+6nq9L48GpV1oPV1xHZe9gGq4YoZYJUokh3bdbM1Y6aBanFzBzYHEu5hbWoiVMRdNLstmHWxM28ggTXqQEy4vw5XzZvxk2UpRaIqDUYCGkcJ12zb84Kmsl89H6/bC48IM+loHapI1cSpB4ZC+B9dP85nZR25MSF1mjm+YQE+cLbWaHzF3XD2b0iu2SJIkB4ZiWNnTF9mHhPwIIatDbI5finlf0+LzeXVuCh81+HizXhwhrmTHcyhmuVUsUGX2MbJuhCzO5IhOzDdUUtD4+gAgyJJFP06kK5VlX8l8HUPexGZQ7rPc+tmsXZnvhxyiP+OW+UkADicqvI+rEbSZLS53OER0bMseAKLeRNBIIGKwOoZ5wTg1SCxITsolxR2r00SEkkAzauYMD4S5MMELsTCA4aY6ogooe1EIIgE//d+bCIYTMF1Uzy9CCAInoDkODWiLzTUnfknWFEoGhBtxgQJXJ/aVgwxUx1MTQ9zpYA5w9ZGKod12FppxRoP5pG1/Jnthy4CKZqRTpoLVuI90k3YbggZdp6LlC/BiORUPaa3T7br++OMxRfBt5oZ7e18y9Cpit47zeXh59KezrbW+J7zSlDXqUFv+mfILPNPy8FrpibZ9XdDGWd39I3qsQkRLkBmy/bnalXLF6CFdE0vYQWzQqe1ahaT7UKfKw5HD4JlKSUI4H3Nbr4oDYBH5OQfJK+K7j/eYMW+lTRKLv/m/gMZLnIXw6zRk5ycKKnL+qjL1OtLm3t1rE/qYSBHxzB1CD7E5s/FgukHydR6ugOD9ubM3gHzsCrHWWaUnYLBU5PEvoSbh2ecx1FnE7sRppa6OI6BtrL9pmnD+MVoBikTqIwqUPDmeI+BJO3fOLlVfIahCD1QpXlqmh1+i3vO8
  template:
    metadata:
      name: cowork-cloudflared-token
      namespace: pinlog-dev
