apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-front-pull
  namespace: pinlog-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBIr2Iifd4csGH7B/76il/c+UT1AaI+32vKIhjCrc5qUETYL+K3NvLA0lZXXzb/xgm5v0PosTcOdvneuKh6la5gaKqCk6H+ZDEnK9k4gprHC5hCoyKHEG0CZquQhWI8KmQwAJUYXJ8ChXBJ82AD8fNhIo0sV2awXFoshlHi3glcy51eE+IQhEUDLd8TXP9AvsyriSzPbLOhRETTCGcy0rhyNAUCc5lDMQEyu0SiovjgHT0sUzYxCrSQnT7mwv7Fu0T76JK+ikfn8WK5vB6p8xkKVU3myvYF9d/onh9CfpsmdSntA53QTni/UVuerxOYrOlVxCtZzxFDgeR1xUYeUpRVEm3LuXL35X53Dd7BR82DSZibtSn8OOBtJXQzIMIGRkSspMy9zkh/6f8YfHB5gUfrCv9yuhl2GCx42nw9Nsu2TELSJ6GI8nCyQLuYWRzxGnauzX0JJNPQw0K8pm4d3l7W9AXpBhjiboNrj18NweEkjNemwVOHkztgaqbhKcjE5clneN263L3ESituyBz9AxiLfHyG5fZa4ONfCVxoE5qpc4RJR7WegvihW3h3DYP7H20MXVZiWZSN2NrkMmEaHvvUHd9AeCwvGEAJCI3jIzQcp1n2RGcyJHvpxwSwVcItP88rWCVwU+2x+31qnrMkHoPkj9P9txcP34bMpJ0gE9pENVqKlbQQU4LKOluKTQiGec25RiCQsSIAu5R/AQpugwGqzuPfrPybla74tyMeySCQXejffrkIv9NfqOx33BVlj2Emw9gi1F/9vqNTML1HekWEEGf/Ot4Be+phnDGjQ/aQtoamYnQIdm+rPae0LcXiHrdnwOm/DU7zs4NEtQf7CwF6M88T/ZbKwOdqO/5W4RSrnPzHDQ7ti0fKVKyTgYwVioDBq6vHc1xXaVZYvOQuHes5kBqvtVbbWYy7O3yf9Vv+Q4kw
  template:
    metadata:
      name: ghcr-front-pull
      namespace: pinlog-dev
    type: kubernetes.io/dockerconfigjson
