---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-front-pull
  namespace: pinlog-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBOrABaYGmDqVN6ZegeQ++buPgetYxDX0yn37qNVVMTh7+Gy2JwGS+oK14E4/8dAuq7UhqFshmS88l9Gg0sqLcmjUQdQoyo5UIK3FpbpVhNtDE5T430Cgb2hvJ28XMChehPCrSGylHDRMGwMOWAWkoYn6CDBhpdtitQLjW7Ebhx0z+rCyRFT1UbrDjk8NgMVF3TMsxwvLKZTBcbIr/wtvIAQrq8GGl+5+h9vJJd/QxXEZt6HQar1ZmKY7sljwhSzXn/3xbCNkpOxvTZVEUb9IMcWPGEKTF+Wq2b/TctDWVZW4c6VMznIs0XkPTZ2TahDXBzls9OHrH8MshrLNf/N/JsKhtLPTKxFi1opfIIkIRUDyrn314Id8GquW5trOilPr/+TxgPpxD+5v3/qWS9Q/5bJfDDcjQrrwpEMy0kXUWWxyxSbAkNb+8fVrkB2hLdINUNJtitrWXBh4Np2YskOpnveUD9t1Uotn/J9BQjc7oPTSbb40gWzAwmZ5+7v/QMNwcY/amu5oXd6pHjiyrvBAXvQgGkG9FxAg7ZTyd6Giyx2wJfFOTtPTdjcJ5bVjQJOkW9nV4M7F8sX4d+RFoPJ3kjgQ74kmak3YQTs0tYwomZ2XbQTCS26ZUlzEQMkJTJ+PUdIKZzWolenpAD8W0kPyKmbHQ/T/ErHFpl7NrmwOfOZlQrBqEsLBtuTpdAd3RSSJjmqzewIYKnp8qvaWpyE5xL7lNeXfgDU3NuhAwOhvLYBSTARwM+LyarZ8X7zXT2moK5iranuHA6WV1qdjp1leRUqOpy7mwZjg98z67ioDF+18oGbiRL7UKxQiocOSDOnqB0afFDX64+vSWFlHGyBlZQ900R3idh2w==
  template:
    metadata:
      name: ghcr-front-pull
      namespace: pinlog-dev
    type: kubernetes.io/dockerconfigjson
