apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-ai-pull
  namespace: pinlog-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCJ5eT7rsib6D4Nbku3xDq8SO62znbUI2UjDo8dM8u0cZs5Ol/GYh4GrxKnc7pERz8n1dJe4RObPrl4aDeTICNO/d4h6ksxlFFzyzUfSARyUYGTtONRkiWSLKszsXAKHHLl3I5NM9TmN1JWGymMMuHk5fw+60q5bzAUYOanmgc89mwBYmLzX4MCBL+r0ixyLQkpJy8SSB+uGCfctJ+iaGh8PN8CGgy1JiXdZlS5MlV5Q2ojipn7zQoJclz68pp5wkgVM9aN0mG0gyToZNBmlZLviruvvUnFrwKtb1aiWRJBrvubqiwzRSr7l0pu9ezJr08CrO4RhWoZOTX5/gUGe8iXT+OTXNdWdNqDwljmXl+L7d/vQdBM1QM/mj2Y7O+7mPF05zElgvTa8jSFPZWCJgjPohLrAf99UlgW3SrCS4tyJX36TWkmIr1c3bcfezo3EPPOwl+NoXBh1mG/yM4gStxp+87CHr3D8XdRa5oq9LZ3jPYfai6mRWrqL+7XNmEzWtzZL4atx936N41rO9ADBmyQ0zJgMkq60yWJ40upUA+HQEqXUppcCMW7TqVUHNX0//SS9qpuxY1F5/1HUGMWxJ1FQ/FFwmi1yjTTIeRmJu8BoeR3gFIXzKCtx4Gsb8wtxpDV9oUnAKhIxvcFWZmFV3V8VfdoO/0QgS6Bn55+jzCkp5wYyYWBNkA3Fgzl8mg2AanXADjhM4eMJp5LPoFuP1OeyxwSD/Y0SOFB+fag0Z2+cuw58Kp+2cirIMRm4HmrVWR3IWsr1w5hzVpFcPu2qpWj/zEGvjK2Kwi8pCUwgAdJy/O3JwxPwOKv9Ptl+LNc1Oe2bR3loUxR/jlovsvbtkUyaQmih9Y6qj+JNpQHoSL1K7xG3utceHXTunTkJ/pckjkAsspeBpoPVknV69gcgBnmRaalz0sq5MDMRsPocp/n6Ilz
  template:
    metadata:
      name: ghcr-ai-pull
      namespace: pinlog-dev
    type: kubernetes.io/dockerconfigjson
