---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-ai-pull
  namespace: pinlog-dev
spec:
  encryptedData:
    .dockerconfigjson: AgB7+ibneVn+frgrfIDnFh0+MQqneknVU80DQYfscdF93QgyDBlZoBuRUpHlxZUeJb8t1WZvtsPJq/Uhuoz1bYQvo30wU/iG42w8ykQFtKWvidOQeTTYcjUds5S7sDV9BasYKWDzVGr2tGrFDhLqXZg0bJ6hOg+8j9QT/IXLiMJWHHPoCdgWvnpajBZq2fvhy+BvHCQVLwJ+/P/ysjVyPCyf6F7FQLrRqWnx89FGeoRBKOm/Yz74A7GyJlr5+fvfvYH6vmdmTfOs0DNe6Mod6bzIqVbdKbH4hO8dzShGFYJo1uwa0Pof2A9SpHCHPoQrD7JVwbwSJhPz2Tc9WokEclVLcpeyigmWVa3meGMggfBPiUjnlkSyaMGhLlwXHJghlgXZWh+4ipkkU+V7XtRlhf74eUFJf2whWyKsA3rXBmG0Lqj3qWJRNovFcQ4l5oL+cThHVDM4FxuFzGkX9SsHCFxn68y1C1uDWG8ZF6VIKQGVhF/OSBtdbYtMix4mEuug4OhHtvbJI37mLDxgsBQWgeVPcTLairnIrw9N7UQFgsDASq3wlBn2u/FLZot01fiJ9bTWqfGbdswkBbxKMZ/J/KyxHNEd8lJAE51MRpdKxwDy74fdQvs4Oro8iz8rBqBpF5qPh3vQrJnXDOl3+b4rmQlgTX8iACuh9yQNofUVJ8mZ4ZN29SC8SbxrgCG7oekJBbp+75HROvRz5nXW4ISQzZZdRASgy/fHXGY52z5za9I4kZeNx7Y4FxW0H9bEHs1tY7S3dA5X++MXp/UMfRW2Q8GdsrWcQyUu0I1VpOIKdm32RjzVjBKf3rS0M2l/HcJnUVs7wNNrbjGhnY49HcIdG6wsnku6aLAFLg==
  template:
    metadata:
      name: ghcr-ai-pull
      namespace: pinlog-dev
    type: kubernetes.io/dockerconfigjson
