---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-cowork-pull
  namespace: pinlog-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAs3MSnpkkzwR6mZRYWXXBHyZu5rBYdScWUYZNqIX0h0WP2XGqOxidTZnMohGUombx34a7Ar/psMz3aqWE3yAw1Rc9h6u68BOW4umpDsy9TtB61R1ywYB6HXaMRLQrRslcJhmZg+JiYlAtaVnEqpTfrOw/Ponz+J5txLNQow3VQZtRBh9sdK3idAx4dpReR2EX2bn8EN5Fmu+XhPXK9hGvVWuDXqL5Tu0PFzhLrBNrWy0IY2WL32Mk8woSlBPGlD+orxBxCVnAjZ608qaWhGzFWRbctg+VprGlrrkhC1asKwMdoLmODgatxLFyr9ZpP9NV1r84QdJcOAxBLi2/q70CGArV9asKE49WpzReb0ECSNc1JCnn/AKGseo5B81dLnsOWC3WZNPdIyCIFDGT0Sfh+ljSk7Gaw3mtbyXk4CgXhXSYRHGkSy4vsWKZE+m/0NjuSce17Hw8uZbHGsuJ2OZmoYt342ww4Nuc0OY+LN+Yf57NO5mNteZujL1FeUW6GoqJlL9dHPm7nctUNEIIIM5x9rw2PKa/zWgZFIIxA1m+PVJsIrk4dGsQ3I7hlWL3A/pxD+6+YTzHIUYFaHFp78dkeh4cKWsZ50EYFaWf0OKLyh1TLWie+J51q5GpPUXuMxQILiV1IxnlRjzWSc0sskpJIQqYKdpcJg1RRS8XJ7H+hndTirc28Hcw0rU21tAXr3VckT1BBqfM6Occc/+w+lC890VEgyL6yCUgrsQ9hyRUI0B7ta2yxPe2sHO30uYCpuTl/H7ILEjSMf+tm9KEDmSr1egEk9F1ArgettfaomViRlYlvTeupKRR4TnH1o0cnz7GdWKMmty8JswGMRry5XgeFBtr43qFj65RSnNeYpFxF73n9R9lYSz+sdsHqS9CzLaO1RW20KiLkOB1ViQ2nQ+7FEn2JWcFvEhUFtysHVdYACMxM
  template:
    metadata:
      name: ghcr-cowork-pull
      namespace: pinlog-dev
    type: kubernetes.io/dockerconfigjson
