---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pinlog-web-cloudflared-token
  namespace: pinlog-dev
spec:
  encryptedData:
    token: AgChYh8LRCND6ule93hQRhw5tvVNukslG7hl2Y3rwZBJS6/G7W3RU6YCvSwc6vwgJjOkaKO2JeKZhRSGmVU7v2EiA+0R/Nz5kG4s9DSdieB/QamUtz3bwyy35HYsTq4DhNeJGsvZO/+lD5lH4rssB5SPayDTCYzTVr7BMtMAmOK9KEGp4bWNxCEeQl+RVtwIu5jtT7MRgStZPFRTBzaSswo0vgTXmUQJBuw8lj6nrEgaM1+OggjA/uP29goRYdL+g02RwLLeTG2JQ02eaaWpkvVyOx75yCSk/h3+Tc0xS/HPJToU5aqJsMcwvmTLv4MPVad2rkoizSLLmAsZRUpnroocUFgYGvtCeXhi+AZAfOLIiv2yP/7BvIYQkN3QPWLFoLHROju2WJijFo6hNAsdYe1I7xVdTiTrqWaHGvkcTlZk6uelaVYZnvZMKdSG0Hf9gNCEbSySQGN0/s+blUuUj0cM0jBj7ZsT0zg5y1AVxX5dhX/mV7ItQBBMZPFs+2eKi51ZW8H41RBgHaa1k/ldgAhk1YGNkPk7a0TntTshHKkTT6KSTccXHN/dvbasK/oT7Zffvrcxaw8lnGr2MLLct85/FZoP7iIQIFlkP0QrAu8TVEXToD2Jy+yxk+pFQfDr9Ps4HdbzOhwgvFNy8FK9FBWJY1CqzaNHoLHliT+kxyWnI/AO2ctMpCB/aD9rNukm+MCOQjVgzrEyPjxhiURPgdQ+3GmuLdvHH+eE1zMW++uRcH10/kQbCYZYPv7sznazsZ6ah58LLpv/OL6uCVqycmbQnO4QwCa0w4TVqhqKie/ElXYolNsRl9CkGUr/Uj+Ls9TwIqt5PgemEpTctdyIrsOmcAPg5KThCi4Oq2Wc/4JDorwSc4+pO3NJg1PqrdPX2YIs3YPZ82uSkMUVDId9ZGMZWpEwFSawZl4s/LpD8p0s8iL245uQx3pz
  template:
    metadata:
      name: pinlog-web-cloudflared-token
      namespace: pinlog-dev
